import {failed,json,db,ApiError,runtime} from '@/lib/server';
import {context,requireAccess,allowed,SHARED_KEY,loadShared,targetProject} from '@/lib/collaboration';
export async function POST(request:Request){try{
 const c=await context(request,true);const bucket=runtime().BUCKET;if(!bucket)throw new ApiError(503,'Document storage is unavailable.');const form=await request.formData();const file=form.get('file');if(!(file instanceof File))throw new ApiError(400,'Choose a file to import.');if(file.size>15*1024*1024)throw new ApiError(413,'Choose a file smaller than 15 MB.');if(!['pdf','docx','xlsx','txt','md','csv','json','zip'].includes(file.name.split('.').pop()?.toLowerCase()||''))throw new ApiError(400,'Import PDF, Word, Excel, text, markdown, CSV or chat JSON.');
 const category=String(form.get('category')||'historic'),projectId=String(form.get('projectId')||'global');if(!['itt','historic','financial','tupe','staffing','completed'].includes(category))throw new ApiError(400,'Choose a document category.');const target=category==='itt'?'_itt':category==='tupe'||category==='staffing'?'_model':category==='completed'?'_bid':'_fmt';
 if(projectId==='global'){if(c.me.role!=='master')throw new ApiError(403,'Only the master user can add shared historical files.');}else if(category==='completed'){if(c.me.role!=='master')throw new ApiError(403,'Only master users can add completed bid files.');const state=await loadShared(c);if(!state.workspace.projects.some(p=>p.id===projectId)&&!await db().prepare('SELECT id FROM bid_archives WHERE id=?').bind(projectId).first())throw new ApiError(404,'Bid not found.');}else {const state=await loadShared(c);targetProject(state.workspace,projectId,target);if(category==='historic'&&c.me.role!=='master')throw new ApiError(403,'Only the master user can add reusable historical evidence.');requireAccess(c,projectId,target,'write');}
 const id=crypto.randomUUID();await bucket.put(`${SHARED_KEY}/${id}`,await file.arrayBuffer(),{httpMetadata:{contentType:file.type||'application/octet-stream'}});
 try{await db().prepare('INSERT INTO files (id,owner_id,name,size,mime,created_at,project_id,category,target_id,visibility) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id,SHARED_KEY,file.name.slice(0,300),file.size,file.type||'application/octet-stream',new Date().toISOString(),projectId,category,target,category==='completed'?'master':'team').run();}catch(e){await bucket.delete(`${SHARED_KEY}/${id}`);throw e;}return json({id,name:file.name,size:file.size});
}catch(e){return failed(e);}}
export async function GET(request:Request){try{
 const c=await context(request);const id=new URL(request.url).searchParams.get('id');if(!id)throw new ApiError(400,'Choose a file.');const record=await db().prepare('SELECT * FROM files WHERE id=?').bind(id).first<any>();if(!record)throw new ApiError(404,'Source file not found.');
 if(c.me.role!=='master'){
  if(record.visibility==='master')throw new ApiError(404,'Source file not found.');if(record.category==='legacy')throw new ApiError(404,'Source file not found.');
  if(record.category==='tupe'||record.category==='financial'||record.category==='staffing'){if(!allowed(c,record.project_id,'_model')&&!allowed(c,record.project_id,'_fmt'))throw new ApiError(404,'Source file not found.');}
  else if(record.project_id!=='global'&&!c.assignments.some(a=>a.projectId===record.project_id&&a.memberId===c.me.id))throw new ApiError(404,'Source file not found.');
 }
 const file=await runtime().BUCKET?.get(`${record.owner_id}/${id}`);if(!file)throw new ApiError(404,'Source file unavailable.');return new Response(file.body,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(record.name)}`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
}catch(e){return failed(e);}}
