import {unzipSync,strFromU8,strToU8,zipSync} from 'fflate';
import type {Question,Workspace,Collaboration} from './types';

const xml=(s:string)=>new DOMParser().parseFromString(s,'application/xml');
const nodes=(d:Document|Element,name:string)=>Array.from(d.getElementsByTagNameNS('*',name));
function zipContents(bytes:Uint8Array){let total=0;return unzipSync(bytes,{filter(entry){total+=entry.originalSize;if(entry.originalSize>15*1024*1024||total>40*1024*1024)throw new Error('This compressed document is too large to extract safely. Import a smaller document.');return true;}});}
export async function extractFile(file:File):Promise<{text:string;warning:string}> {
 const ext=file.name.split('.').pop()?.toLowerCase();if(file.size>15*1024*1024)throw new Error('Choose a file smaller than 15 MB.');let text='';let warning='';
 if(['txt','md','csv'].includes(ext||''))text=await file.text();
 else if(ext==='json'){const data=JSON.parse(await file.text());if(Array.isArray(data)&&data.some(x=>x.mapping)){text=data.map(c=>{const mapping=c.mapping||{};const chain:any[]=[];let at=c.current_node;const seen=new Set<string>();while(at&&mapping[at]&&!seen.has(at)){seen.add(at);chain.unshift(mapping[at]);at=mapping[at].parent;}return `[Chat: ${c.title||'Untitled'}]\n`+chain.map(n=>{const m=n.message;return m?`${m.author?.role||'message'}: ${(m.content?.parts||[]).filter((p:unknown)=>typeof p==='string').join('\n')}`:'';}).filter(Boolean).join('\n\n');}).join('\n\n');warning='Chat extracts are working context. Check facts and approvals before drafting.';}else{text=JSON.stringify(data,null,2);warning='JSON text imported. Check that the relevant messages and source details are present.';}}
 else if(ext==='docx'){const files=zipContents(new Uint8Array(await file.arrayBuffer()));if(!files['word/document.xml'])throw new Error('The Word document has no readable document body.');const d=xml(strFromU8(files['word/document.xml']));text=nodes(d,'p').map(p=>nodes(p,'t').map(t=>t.textContent||'').join('')).join('\n');warning='Word body text extracted. Review tables, headers, images and tracked changes in the original.';}
 else if(ext==='xlsx'){const files=zipContents(new Uint8Array(await file.arrayBuffer()));const shared=files['xl/sharedStrings.xml']?nodes(xml(strFromU8(files['xl/sharedStrings.xml'])),'si').map(i=>nodes(i,'t').map(t=>t.textContent||'').join('')):[];const workbook=files['xl/workbook.xml']?xml(strFromU8(files['xl/workbook.xml'])):null;const relations=files['xl/_rels/workbook.xml.rels']?xml(strFromU8(files['xl/_rels/workbook.xml.rels'])):null;const targets=new Map((relations?nodes(relations,'Relationship'):[]).map(r=>[r.getAttribute('Id'),r.getAttribute('Target')]));const sections:string[]=[];for(const sheet of workbook?nodes(workbook,'sheet'):[]){const rid=sheet.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id');const target=targets.get(rid);const path=target?.startsWith('/')?target.slice(1):'xl/'+target?.replace(/^\.\//,'');if(!target||!files[path])continue;const d=xml(strFromU8(files[path]));const rows=nodes(d,'row').map(row=>{return nodes(row,'c').map(c=>{const type=c.getAttribute('t');const value=nodes(c,'v')[0]?.textContent||'';const formula=nodes(c,'f')[0]?.textContent;let val=type==='s'?shared[Number(value)]||'':type==='inlineStr'?nodes(c,'t').map(t=>t.textContent||'').join(''):value;return `${c.getAttribute('r')}: ${val}${formula?` [formula: ${formula}; cached value, not recalculated]`:''}`;}).join(' | ');}).filter(Boolean);sections.push(`[Sheet: ${sheet.getAttribute('name')}]\n`+rows.join('\n'));}text=sections.join('\n\n');warning='Excel cells and cached values imported. Formulas have not been recalculated; confirm the governing facts in the original workbook.';}
 else if(ext==='pdf'){const pdfjs=await import('pdfjs-dist');pdfjs.GlobalWorkerOptions.workerSrc='/pdf.worker.min.mjs';const task=pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())});const pdf=await task.promise;const pages:string[]=[];for(let i=1;i<=Math.min(pdf.numPages,180);i++){const page=await pdf.getPage(i);const content=await page.getTextContent();pages.push(`[Page ${i}]\n`+content.items.map(item=>'str' in item?item.str+(item.hasEOL?'\n':' '):'').join(''));}text=pages.join('\n\n');await task.destroy();warning='PDF text extracted. Scanned pages and diagrams need a text extract or manual review.';}
 else throw new Error('Import PDF, DOCX, XLSX, TXT, MD, CSV or JSON. Unzip archives and select a relevant document first.');
 if(!text.trim())throw new Error('No readable text was found. Paste a checked extract or use a text-enabled document.');if(text.length>120000){text=text.slice(0,120000);warning+=' Only the first 120,000 characters were retained. Import focused extracts for the remaining content.';}
 return {text,warning};
}
export function download(data:BlobPart,name:string,mime='text/plain'){const blob=new Blob([data],{type:mime});const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const esc=(t:string)=>t.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
export function wordBytes(title:string,body:string){const p=(text:string,bold=false)=>`<w:p><w:r>${bold?'<w:rPr><w:b/><w:sz w:val="28"/></w:rPr>':''}<w:t xml:space="preserve">${esc(text)}</w:t></w:r></w:p>`;const doc=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${p(title,true)}${body.replace(/\r\n?/g,'\n').split('\n').map(s=>p(s)).join('')}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134"/></w:sectPr></w:body></w:document>`;return zipSync({'[Content_Types].xml':strToU8('<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>'),'_rels/.rels':strToU8('<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'),'word/document.xml':strToU8(doc)});}
export function exportWord(q:Question,review=false){const name=`${q.ref}-${q.title.replace(/[^a-z0-9]+/gi,'-')}${review?'-REVIEW':''}.docx`;download(wordBytes(`${q.ref} ${q.title}${review?' — Review copy':''}`,q.draft).slice().buffer,name,'application/vnd.openxmlformats-officedocument.wordprocessingml.document');}
export function exportPack(questions:Question[],w:Workspace,c?:Collaboration){const entries:Record<string,Uint8Array>={};const summary=['Question,Words,Characters,Limit,Unit,Status'];for(const q of questions){entries[`${q.ref.replace(/[^a-z0-9-]/gi,'-')}-${q.id.slice(0,8)}.docx`]=wordBytes(`${q.ref} ${q.title} — Review copy`,q.draft);summary.push([q.ref,q.draft.trim().split(/\s+/).filter(Boolean).length,Array.from(q.draft).length,q.limit,q.unit,q.status].join(','));}if(c)entries['review-history.json']=strToU8(JSON.stringify({comments:c.comments,checks:c.checks,audit:c.audit,assignments:c.assignments},null,2));entries['counts.csv']=strToU8(summary.join('\n'));entries['workspace-backup.json']=strToU8(JSON.stringify(w,null,2));download(zipSync(entries).slice().buffer,'DRPA-bid-review-pack.zip','application/zip');}
