import type {Project,PostBidReview,Member} from './types';
import {deadlineInstant} from './deadlines';
export const emptyPostBid=():PostBidReview=>({outcome:'pending',commissionerFeedback:'',wentWell:'',improvements:'',systemUse:'',teamFeedback:'',delays:[],actions:[],contributions:[]});
export function postBidStats(p:Project,events:any[],comments:any[],members:Member[]){
 const people=new Map<string,{id:string;name:string;role:string;first:string;last:string;draftSaves:number;modelSaves:number;checks:number;commented:number;decisions:number;approvals:number}>();
 const person=(id:string,name:string,role:string)=>{const key=id||'legacy-'+name;if(!people.has(key))people.set(key,{id:key,name:name||'Unrecorded user',role:role||members.find(m=>m.id===id)?.role||'Legacy role not recorded',first:'',last:'',draftSaves:0,modelSaves:0,checks:0,commented:0,decisions:0,approvals:0});return people.get(key)!;};
 for(const e of events){const r=person(e.actor_id,e.actor_name,e.actor_role);if(!r.first||e.created_at<r.first)r.first=e.created_at;if(!r.last||e.created_at>r.last)r.last=e.created_at;if(/First draft saved|Edited answer|Updated question inputs/.test(e.action))r.draftSaves++;if(/Updated service model|Updated FMT inputs|Exported costed FMT|Validated FMT mapping/.test(e.action))r.modelSaves++;if(e.action==='Checked current version')r.checks++;if(/^Marked complete/.test(e.action))r.approvals++;}
 for(const e of comments){person(e.author_id,e.author_name,'').commented++;if(e.decided_by)person(members.find(m=>m.name===e.decided_by)?.id||'',e.decided_by,'').decisions++;}
 const timings=p.questions.map(q=>{const ee=events.filter(e=>e.target_id===q.id),first=ee.find(e=>e.action==='First draft saved')?.created_at||'',sent=ee.find(e=>e.action==='Sent for review')?.created_at||'',checked=ee.find(e=>e.action==='Checked current version'&&(!sent||e.created_at>=sent))?.created_at||'',approved=[...ee].reverse().find(e=>/^Marked complete/.test(e.action))?.created_at||'';const reviewHours=sent&&checked?(Date.parse(checked)-Date.parse(sent))/3600000:null;return {id:q.id,ref:q.ref,title:q.title,firstDraft:first,sentForReview:sent,firstCheck:checked,approved,reviewHours,reopens:ee.filter(e=>e.action==='Reopened draft').length};});
 const open=comments.filter(e=>e.status==='open'||e.status==='accepted'&&!e.applied),now=Date.now(),waits=open.map(e=>({targetId:e.target_id,days:Math.max(0,(now-Date.parse(e.created_at))/86400000)}));const deadline=deadlineInstant(p.deadline),submitted=p.submittedAt?Date.parse(p.submittedAt):null;const lateMinutes=deadline!==null&&p.deadline?.confirmed&&submitted!==null?(submitted-deadline)/60000:null;const known=timings.filter(t=>t.reviewHours!==null);const recommendations:string[]=[];if(open.length)recommendations.push(`Review ${open.length} unresolved comment(s), identifying the missing decision or evidence and an owner.`);if(known.some(t=>t.reviewHours!>48))recommendations.push('Discuss review waits over 48 hours and agree an earlier handover or reserve checker. Saved timestamps measure elapsed time, not hours worked.');if(timings.some(t=>t.reopens))recommendations.push('Review reopened answers for changes to scope, evidence or financial assumptions; agree a shared freeze point.');if(timings.some(t=>!t.firstDraft))recommendations.push('Some first-draft activity was not recorded in this version. Ask the team about work completed outside the system before drawing conclusions.');if(lateMinutes!==null&&lateMinutes>0)recommendations.push('Review the recorded submission delay, the confirmed deadline and any portal constraints; agree an internal submission buffer.');if(!p.submittedAt)recommendations.push('Record the actual portal submission date and confirmation reference before assessing deadline performance.');recommendations.push('Use specific examples in feedback: contribution, effect on the bid, support needed, and an action with an owner and due date.');
 return {contributions:[...people.values()],timings,commentSummary:{total:comments.length,accepted:comments.filter(x=>x.status==='accepted').length,rejected:comments.filter(x=>x.status==='rejected').length,open:open.length,oldestOpenDays:waits.length?Math.max(...waits.map(x=>x.days)):0},usage:{recordedEvents:events.length,draftSaves:events.filter(e=>/First draft saved|Edited answer/.test(e.action)).length,verifiedDocuments:events.filter(e=>e.action==='Verified bid document').length,fmtExports:events.filter(e=>e.action==='Exported costed FMT').length,checks:events.filter(e=>e.action==='Checked current version').length,reopens:events.filter(e=>e.action==='Reopened draft').length},lateMinutes,recommendations,limitation:'Saved activity is an audit trail, not time tracking or a measure of writing quality. Earlier events may lack role attribution; offline work and reasons for waits require team input.'};
}
