import sourceSeed from './source-seed.json';
import questionSeed from './question-seed.json';
import type {Workspace,Question,Source} from './types';
export const defaultRules=`Use the exact tender question and current scoring criteria. Write readable commissioner-friendly UK English with direct answers, delivery ownership and assurance. Use relevant experience with site, timeframe, action, result and evidence. Target 95–98% of the permitted count when useful content supports it. Never fabricate question numbers, limits, results, policies, partners or commitments.
The bid-designated financial model controls funded roles, WTEs, deployment, hours, sessions, partners and costs. Earlier models are not authoritative. Refer neutrally to "the financial model" or "the submitted financial model", without filenames or version labels in submission prose. Cross-check delivery, recruitment, finance and governance answers. Do not promise unsupported 24/7 coverage or duplicate workforce costs.
DRPA's user-reported subcontractor footprint includes NHFT, CNWL and Oxleas. Ashtons is a pharmacy/medicines partner, not a site. Oakhill and CQC improvement claims require supporting records. Verify the period and definition of turnover and workforce figures. Use ARC only where confirmed for the bid; confirm the acronym expansion rather than guessing.
Earlier chat extracts and answers are working context until approved. A prior proposed staffing model is not proof of actual delivery. Treat historical tender packs and clarifications as bid-specific. Show gaps and assumptions separately. Export clean documents without comments or tracked changes. Final approval requires human review of evidence, requirements, funded commitments and portal counting.`;
export function newQuestion(ref='Q01',title='New question'):Question{return {id:crypto.randomUUID(),ref,title,text:'',limit:null,unit:'characters',includeSpaces:true,countHeading:false,style:'Commissioner-friendly',structure:'Flowing narrative',criteria:[],input:'',evidenceIds:[],draft:'',status:'draft',versions:[],review:[],notes:''};}
export const workedExample=`DRPA Secure proposes an integrated healthcare model for HMP/YOI Winchester, with clear clinical accountability, coordinated specialist input and care that responds to the risks of early custody. Each commitment will be reconciled to the financial model before submission.

Primary care, mental health, substance misuse, medicines management and relevant partner services will operate within a shared framework. [CONFIRM: services delivered directly and the named, costed specialist partners.] A coordinated care plan and clear escalation arrangements will support continuity between reception, stabilisation, planned care, transfer and release.

Clinical and operational leaders will review demand, incidents, access and outcomes together. [CONFIRM: funded leadership roles, governance arrangements and contractual reporting.] Changes to deployment and clinic capacity will be assessed against the commissioned service and agreed resources.

Early days in custody will receive focused attention through assessment, identification of urgent needs, medicines reconciliation and onward care planning. [CONFIRM: specification timings, funded reception cover and surge arrangements.]

[INSERT EVIDENCE: an approved DRPA mobilisation or integrated-care example with the site, period, action and evidenced outcome.]

This is a worked example. Complete the service allocation, financial-model checks and required pictorial attachments before approving an answer.`;
export function initialWorkspace():Workspace{const questions=(questionSeed as {ref:string;title:string;text:string;limit:number;criteria:string[]}[]).map((s,i)=>({...newQuestion(s.ref,s.title),...s,id:`q0${i+1}`,draft:i===0?workedExample:'',notes:'Historical Winchester ITT question, pages 2–3. Reconfirm wording and limits in the current portal.'}));return {schemaVersion:1,projects:[{id:'winchester',name:'HMP/YOI Winchester',commissioner:'NHS England South East',scope:'Integrated healthcare · Lot 2 · historical bid workspace',modelSourceId:null,facts:[],questions}],sources:sourceSeed as Source[],rules:defaultRules,updatedAt:new Date().toISOString()};}
