import {z} from 'zod';
const id=z.string().min(1).max(100);
const money=z.number().finite().min(0).max(1e10).nullable();
const pct=z.number().finite().min(0).max(100).nullable();
const stage=z.enum(['draft','review','approved']);
const staff=z.object({id,service:z.string().max(300),role:z.string().max(300),provider:z.string().max(300),grade:z.string().max(100),basis:z.enum(['wte','coverage']),wte:z.number().min(0).max(10000).nullable(),weeklyCoverage:z.number().min(0).max(100000).nullable(),fteHoursWeek:z.number().min(1).max(168),productiveWeeks:z.number().min(0).max(54).nullable(),salaryFte:money,allowanceFte:money,niPct:pct,niThreshold:money,pensionPct:pct,otherFte:money,escalationPct:pct});
const tupe=z.object({id,reference:z.string().max(150),role:z.string().max(300),staffLineId:z.string().max(100),fte:z.number().min(0).max(2).nullable(),salaryFte:money,allowanceAnnual:money,niPct:pct,niThreshold:money,pensionPct:pct,otherAnnual:money,include:z.boolean(),verified:z.boolean(),notes:z.string().max(3000)});
export const modelSchema=z.object({narrative:z.string().max(40000),pathways:z.array(z.object({id,name:z.string().max(300),description:z.string().max(6000),questionIds:z.array(id).max(80)})).max(30),staff:z.array(staff).max(150),tupe:z.array(tupe).max(250),nonPay:z.array(z.object({id,label:z.string().max(300),kind:z.enum(['recurring','mobilisation','capital']),amount:money,escalationPct:pct,capitalTreatment:z.enum(['year1','amortise']),amortisationYears:z.number().int().min(1).max(10).nullable()})).max(150),contractYears:z.number().int().min(1).max(10),weeksPerYear:z.number().min(48).max(54),tupeAssumption:z.enum(['unknown','none','provided']),overheadPct:pct,profitPct:pct,pricingMethod:z.enum(['markup','margin']),annualBudget:money,status:stage,tupeFiles:z.array(z.object({id,name:z.string().max(300),sheet:z.string().max(150),payBasis:z.string().max(100)})).max(20).optional(),staffFiles:z.array(z.object({id,name:z.string().max(300),sheet:z.string().max(150),importedAt:z.string().max(100)})).max(20).optional(),assumptions:z.string().max(12000)});
export const fmtSchema=z.object({fileId:id.nullable(),name:z.string().max(300),fingerprint:z.string().max(100),sheets:z.array(z.object({name:z.string().max(150),rows:z.number().int().min(0).max(1048576),columns:z.number().int().min(0).max(16384)})).max(100),mappings:z.array(z.object({id,metric:z.enum(['staff_wte','staff_cost','nonpay_cost','total_staff','total_nonpay','overhead','profit','price']),lineId:z.string().max(100),year:z.number().int().min(1).max(10),sheet:z.string().min(1).max(150),cell:z.string().regex(/^[A-Za-z]{1,3}[1-9][0-9]{0,6}$/),verified:z.boolean()})).max(3500),status:stage,validatedHash:z.string().max(100),validationNote:z.string().max(4000),outputFileId:id.nullable().optional(),exportedHash:z.string().max(100),mode:z.enum(['mapped','completed']).optional(),completedFacts:z.array(z.object({id,label:z.string().min(1).max(300),sheet:z.string().min(1).max(150),cell:z.string().regex(/^[A-Za-z]{1,3}[1-9][0-9]{0,6}$/),verified:z.boolean()})).max(80).optional()});
export const briefSchema=z.object({summary:z.string().max(12000),deadline:z.string().max(2000),contractTerm:z.string().max(2000),budget:z.string().max(2000),topics:z.array(z.string().max(300)).max(50),requirements:z.array(z.object({id,title:z.string().max(500),excerpt:z.string().max(3000),sourceId:z.string().max(100)})).max(80),gaps:z.array(z.object({id,title:z.string().max(300),detail:z.string().max(4000),priority:z.enum(['high','medium']),state:z.enum(['open','in_progress','confirmed']),ownerId:z.string().max(100),dueDate:z.string().max(100),evidence:z.string().max(3000)})).max(80),sourceIds:z.array(id).max(100),generatedAt:z.string().max(100)});

const review=z.object({id:z.string().max(100),severity:z.enum(['high','medium','info']),title:z.string().max(500),detail:z.string().max(6000)});
const question=z.object({id:z.string().max(100),ref:z.string().max(100),title:z.string().max(500),text:z.string().max(40000),limit:z.number().int().min(1).max(100000).nullable(),unit:z.enum(['words','characters']),includeSpaces:z.boolean(),countHeading:z.boolean(),style:z.string().max(100),structure:z.string().max(100),criteria:z.array(z.string().max(2500)).max(40),input:z.string().max(40000),evidenceIds:z.array(z.string().max(100)).max(60),draft:z.string().max(100000),status:z.enum(['draft','review','approved']),versions:z.array(z.object({id:z.string().max(100),text:z.string().max(100000),createdAt:z.string().max(100),action:z.string().max(100)})).max(12),review:z.array(review).max(80),notes:z.string().max(12000)});
export const workspaceSchema=z.object({schemaVersion:z.literal(1),updatedAt:z.string().max(100),rules:z.string().max(30000),sources:z.array(z.object({id:z.string().max(100),name:z.string().max(300),text:z.string().max(120000),kind:z.string().max(80),scope:z.string().max(100),status:z.enum(['approved','needs_verification','catalogued']),locator:z.string().max(2000),createdAt:z.string().max(100),fileId:z.string().max(100).nullable().optional(),category:z.enum(['itt','historic','financial','tupe','completed','intelligence']).optional(),visibility:z.enum(['team','master']).optional(),origin:z.object({kind:z.enum(['intelligence','completed_bid']),recordId:z.string().max(200),period:z.string().max(100),version:z.string().max(100),retrievedAt:z.string().max(100),projectId:z.string().max(100)}).optional()})).max(60),projects:z.array(z.object({id:z.string().max(100),name:z.string().max(300),commissioner:z.string().max(300),scope:z.string().max(3000),modelSourceId:z.string().max(100).nullable(),deadline:z.object({date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),time:z.string().regex(/^(?:[01]\d|2[0-3]):[0-5]\d$/),timezone:z.literal('Europe/London'),sourceId:z.string().max(100),locator:z.string().max(2000),confirmed:z.boolean(),updatedAt:z.string().max(100)}).optional(),submittedAt:z.string().max(100).optional(),submissionNote:z.string().max(2000).optional(),brief:briefSchema.optional(),serviceModel:modelSchema.optional(),fmt:fmtSchema.optional(),facts:z.array(z.object({id:z.string().max(100),label:z.string().max(300),value:z.string().max(2000),locator:z.string().max(1000)})).max(80),questions:z.array(question).max(80)})).max(20)});
export const generationSchema=z.object({answer:z.string().max(100000),gaps:z.array(z.object({title:z.string().max(500),detail:z.string().max(6000),severity:z.enum(['high','medium','info'])})).max(40),evidence:z.array(z.object({sourceId:z.string(),locator:z.string(),claim:z.string()})).max(40),commitments:z.array(z.string()).max(40),criteriaReview:z.array(z.object({criterion:z.string(),status:z.enum(['addressed','partial','missing']),explanation:z.string()})).max(40)});

export const postBidSchema=z.object({outcome:z.enum(['pending','won','lost','withdrawn','no_bid']),commissionerFeedback:z.string().max(12000),wentWell:z.string().max(12000),improvements:z.string().max(12000),systemUse:z.string().max(12000),teamFeedback:z.string().max(16000),delays:z.array(z.object({id,issue:z.string().max(2000),impact:z.string().max(2000),reason:z.string().max(2000),remedy:z.string().max(2000),owner:z.string().max(200)})).max(40),actions:z.array(z.object({id,action:z.string().max(2000),owner:z.string().max(200),dueDate:z.string().max(100),status:z.enum(['open','done'])})).max(40),contributions:z.array(z.object({id,memberId:id,strength:z.string().max(2000),support:z.string().max(2000)})).max(100)});
