import {useEffect,useState} from 'react';
import {MessageSquare,Check,CheckCircle2,Users,Plus,Trash2,Download,ClipboardCheck} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Collaboration,Project,Workspace,Comment,Member} from '@/lib/types';
import {canAccess,contentHash,targetContent} from '@/lib/finance';
import {download} from '@/lib/files';
import {Pick,Tick,when} from './shared';
export type Perform=(path:string,data:Record<string,unknown>)=>Promise<void>;
export const roleLabels={master:'Master user',writer:'Bid writer',checker:'Bid checker'};
export const sectionLabels:Record<string,string>={_itt:'ITT documents',_brief:'Bid briefing and data',_model:'Service model and TUPE',_fmt:'Financial model / FMT'};
export function ReviewPanel({p,w,c,target,perform,problems=[],selectedQuote=''}:{p:Project;w:Workspace;c:Collaboration;target:string;perform:Perform;problems?:string[];selectedQuote?:string}){
 const [text,setText]=useState(''),[quote,setQuote]=useState(''),[proposal,setProposal]=useState(''),[busy,setBusy]=useState(false),[hash,setHash]=useState(''),[decision,setDecision]=useState<{comment:Comment;action:string;decision?:string}|null>(null),[note,setNote]=useState(''),[recalculated,setRecalculated]=useState(false),[approvalNote,setApprovalNote]=useState('');
 const review=canAccess(c,p.id,target),write=canAccess(c,p.id,target,'write'),check=canAccess(c,p.id,target,'check');const comments=c.comments.filter(x=>x.projectId===p.id&&x.targetId===target);const q=p.questions.find(q=>q.id===target);const item=target==='_model'?p.serviceModel:target==='_fmt'?p.fmt:q;
 useEffect(()=>{let cancelled=false;(c.targetHashes?.[p.id+':'+target]?Promise.resolve(c.targetHashes[p.id+':'+target]):contentHash(targetContent(p,target,w))).then(h=>{if(!cancelled)setHash(h);});return()=>{cancelled=true;};},[p,target,w,c.targetHashes]);
 useEffect(()=>{setText('');setQuote('');setProposal('');setApprovalNote('');setRecalculated(false);},[target,p.id]);
 const currentChecks=c.checks.filter(r=>r.projectId===p.id&&r.targetId===target&&r.contentHash===hash);const open=comments.filter(x=>x.status==='open'||x.status==='accepted'&&!x.applied).length;
 async function act(path:string,data:Record<string,unknown>){setBusy(true);try{await perform(path,{projectId:p.id,targetId:target,...data});return true;}catch{return false;}finally{setBusy(false);}}
 return <section className="collab-panel"><div className="panel-title"><div><span className="eyebrow">REVIEW AND DECISIONS</span><h2>{sectionLabels[target]||`${q?.ref} collaborative review`}</h2></div><span className="tag pale">{open} unresolved · {currentChecks.length} current checks</span></div>
 {item&&<div className="workflow-strip"><span className={'stage '+item.status}>{item.status==='approved'?'Complete':item.status==='review'?'In review':'Draft'}</span>{write&&<button className="btn" disabled={busy} onClick={()=>act('/api/workflow',{action:'submit'})}>Send for review</button>}{check&&<button className="btn" disabled={busy||!!problems.length||!!open} onClick={()=>act('/api/workflow',{action:'check'})}><ClipboardCheck size={16}/>{c.me.role==='master'?'Master check':'Sign off current version'}</button>}{c.me.role==='master'&&<button className="btn primary" disabled={busy||!!problems.length||!!open||target==='_fmt'&&!recalculated} onClick={()=>act('/api/workflow',{action:'approve',confirmRecalculated:recalculated,note:approvalNote})}><CheckCircle2 size={16}/>Mark complete</button>}{write&&item.status!=='draft'&&<button className="btn quiet" disabled={busy} onClick={()=>act('/api/workflow',{action:'reopen'})}>Reopen</button>}</div>}
 {target==='_fmt'&&c.me.role==='master'&&<div className="fmt-attestation"><Tick value={recalculated} change={setRecalculated} label="I reopened the exported FMT, recalculated it and checked its financial summaries."/><label>Financial review record<input value={approvalNote} onChange={e=>setApprovalNote(e.target.value)} placeholder="Reviewer, date and totals checked"/></label></div>}
 {problems.length>0&&<details className="check-details"><summary>{problems.length} checks before sign-off</summary><ul>{problems.slice(0,20).map((t,i)=><li key={i}>{t}</li>)}</ul>{problems.length>20&&<p>Resolve these to reveal the remaining checks.</p>}</details>}
 {review&&<div className="comment-compose"><label>Comment<textarea rows={3} value={text} onChange={e=>setText(e.target.value)} placeholder="Add a specific issue, supporting evidence or proposed improvement."/></label>{q&&<details><summary>Suggest a wording change</summary><label>Exact passage to replace<textarea rows={2} value={quote} onChange={e=>setQuote(e.target.value)}/></label>{selectedQuote&&<button className="text-btn" onClick={()=>setQuote(selectedQuote)}>Use selected passage</button>}<label>Suggested replacement<textarea rows={3} value={proposal} onChange={e=>setProposal(e.target.value)}/></label><p className="hint">The passage must appear once. Accepting the suggestion applies it only if the answer and evidence are still the same version.</p></details>}<button className="btn" disabled={busy||!text.trim()} onClick={async()=>{if(await act('/api/comments',{action:'add',text,quote,proposal})){setText('');setQuote('');setProposal('');}}}><MessageSquare size={16}/>Add comment to this item</button></div>}
 <div className="comment-list">{comments.map(comment=><article key={comment.id} className={'comment '+comment.status}><header><strong>{comment.authorName}</strong><span>{when(comment.createdAt)}</span><span className={'tag '+(comment.status==='rejected'?'pale':comment.applied?'approved':'needs_verification')}>{comment.status==='open'?'Open':comment.status==='rejected'?'Rejected':comment.applied?'Accepted · incorporated':'Accepted · action needed'}</span></header><p>{comment.text}</p>{comment.quote&&<blockquote>{comment.quote}</blockquote>}{comment.proposal&&<div className="suggested-text"><strong>Suggested wording</strong><p>{comment.proposal}</p></div>}{comment.decisionNote&&<p className="decision-note">{comment.decidedBy}: {comment.decisionNote}</p>}{write&&comment.status==='open'&&<div className="bottom-actions"><button className="btn compact" disabled={busy} onClick={()=>{setNote('');setDecision({comment,action:'decide',decision:'accepted'});}}>Accept{comment.proposal?' and apply suggestion':''}</button><button className="btn quiet compact" disabled={busy} onClick={()=>{setNote('');setDecision({comment,action:'decide',decision:'rejected'});}}>Reject with reason</button></div>}{write&&comment.status==='accepted'&&!comment.applied&&<button className="btn compact" onClick={()=>{setNote('');setDecision({comment,action:'incorporate'});}}>Record incorporation / verification</button>}</article>)}{!comments.length&&<p className="empty-copy">No comments on this item yet.</p>}</div>
 <Dialog open={!!decision} onOpenChange={open=>!open&&setDecision(null)}><DialogContent><DialogHeader><DialogTitle>{decision?.action==='incorporate'?'Record how this was addressed':decision?.decision==='rejected'?'Reject this comment':'Accept this comment'}</DialogTitle><DialogDescription>{decision?.comment.proposal&&decision.decision==='accepted'?'The suggested wording will replace the quoted passage if the current version matches.':'Keep a clear record of the review decision.'}</DialogDescription></DialogHeader><label>Decision / action note<textarea rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="Explain the decision or the change/evidence used."/></label><button className="btn primary" disabled={busy||(decision?.action==='incorporate'||decision?.decision==='rejected')&&!note.trim()} onClick={async()=>{if(!decision)return;if(await act('/api/comments',{action:decision.action,id:decision.comment.id,decision:decision.decision,note}))setDecision(null);}}>Save decision</button></DialogContent></Dialog>
 </section>;
}
export function TeamPanel({p,c,perform}:{p:Project;c:Collaboration;perform:Perform}){
 const blank={email:'',name:'',role:'writer' as Member['role'],active:true};const [form,setForm]=useState<Partial<Member>&typeof blank>(blank),[person,setPerson]=useState(''),[target,setTarget]=useState(p.questions[0]?.id||'_model'),[access,setAccess]=useState<'write'|'check'>('write'),[busy,setBusy]=useState(false);
 const targets=[...p.questions.map(q=>({value:q.id,label:q.ref+' · '+q.title})),...Object.entries(sectionLabels).map(([value,label])=>({value,label}))];
 const assignable=c.members.filter(m=>m.active&&(m.role==='master'||m.role===(access==='write'?'writer':'checker')));
 async function act(data:Record<string,unknown>){setBusy(true);try{await perform('/api/team',data);}finally{setBusy(false);}}
 if(c.me.role!=='master')return <section className="model-panel"><h2>Your access</h2><p>{roleLabels[c.me.role]}. You can work on the questions and sections assigned to you. Ask the master user to change assignments.</p></section>;
 return <div className="team-grid"><section className="model-panel"><h2>Users and roles</h2><p>Each person signs in with their own account. Add their exact sign-in email, then assign their work. For this private preview, also grant them access in the Site sharing settings.</p><div className="member-list">{c.members.map(m=><button className="member-row" key={m.id} onClick={()=>setForm(m)}><span className="member-avatar">{m.name.charAt(0).toUpperCase()}</span><span><strong>{m.name}</strong><small>{m.email}</small></span><span className="tag pale">{roleLabels[m.role]}{!m.active?' · inactive':''}</span></button>)}</div><div className="dialog-form"><h3>{form.id?'Edit user':'Add a user'}</h3><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Sign-in email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Role<Pick value={form.role} change={role=>setForm({...form,role:role as Member['role']})} label="User role" items={Object.entries(roleLabels).map(([value,label])=>({value,label}))}/></label><Tick value={form.active} change={active=>setForm({...form,active})} label="Account active"/><div className="bottom-actions"><button className="btn primary" disabled={busy||!form.email||!form.name} onClick={async()=>{await act({action:'member',member:form});setForm(blank);}}>Save user</button>{form.id&&<button className="btn quiet" onClick={()=>setForm(blank)}>Add another user</button>}</div></div></section>
 <section className="model-panel"><h2>Assignments for {p.name}</h2><div className="assignment-form"><label>Permission<Pick value={access} change={v=>{setAccess(v as 'write'|'check');setPerson('');}} label="Assignment permission" items={[{value:'write',label:'Write and resolve comments'},{value:'check',label:'Comment and check'}]}/></label><label>Person<Pick value={person} change={setPerson} label="Assigned person" items={[{value:'',label:'Choose a user'},...assignable.map(m=>({value:m.id,label:m.name}))]}/></label><label>Question or section<Pick value={target} change={setTarget} label="Assigned section" items={targets}/></label><button className="btn primary" disabled={busy||!person} onClick={()=>act({action:'assign',projectId:p.id,targetId:target,memberId:person,access})}><Plus size={16}/>Assign this item</button></div><div className="assignment-list">{c.assignments.filter(a=>a.projectId===p.id).map(a=><div key={a.id}><span><strong>{c.members.find(m=>m.id===a.memberId)?.name||'User'}</strong><small>{targets.find(t=>t.value===a.targetId)?.label||a.targetId}</small></span><span className="tag pale">{a.access==='write'?'Writer':'Checker'}</span><button className="icon-btn" aria-label="Remove assignment" disabled={busy} onClick={()=>act({action:'unassign',id:a.id})}><Trash2 size={17}/></button></div>)}</div><div className="permission-notes"><strong>Master user</strong><p>Manages users and assignments, sees the whole bid and provides final approval.</p><strong>Bid writer</strong><p>Edits assigned answers or sections, submits drafts, and accepts or rejects comments.</p><strong>Bid checker</strong><p>Comments and checks assigned work. Cannot change the draft or mark it complete.</p></div></section></div>;
}
export function AuditPanel({c}:{c:Collaboration}){return <section className="model-panel"><div className="panel-title"><h2>Recent review history</h2><button className="btn" onClick={()=>download(JSON.stringify({audit:c.audit,comments:c.comments,checks:c.checks},null,2),'DRPA-review-history.json','application/json')}><Download size={16}/>Export history</button></div><div className="audit-list">{c.audit.map(a=><div key={a.id}><time>{when(a.createdAt)}</time><strong>{a.actorName}</strong><span>{a.action}</span></div>)}</div></section>;}
