import {useRef,useState} from 'react';
import {Upload,FileText,Sparkles,Plus,Download,Check,Search} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Workspace,Project,Source,Collaboration,Question} from '@/lib/types';
import {extractFile,download} from '@/lib/files';
import {extractQuestions,buildBrief,type QuestionCandidate} from '@/lib/itt';
import {canAccess} from '@/lib/finance';
import {ReviewPanel,type Perform} from './collaboration';
import {Pick,Tick,when} from './shared';
import {DeadlinePanel,DeleteAction} from './lifecycle';
export function IntakePanel({p,w,c,change,persist,openQuestion,perform,edit}:{p:Project;w:Workspace;c:Collaboration;change:(fn:(w:Workspace)=>void)=>void;persist:()=>Promise<void>;openQuestion:(id:string)=>void;perform:Perform;edit:(patch:Partial<Project>)=>void}){
 const input=useRef<HTMLInputElement>(null);const [busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<{file:File;text:string;warning:string}[]>([]),[candidates,setCandidates]=useState<QuestionCandidate[]>([]),[selectedSources,setSelectedSources]=useState<string[]>([]);
 const sources=w.sources.filter(s=>s.scope===p.id&&s.category==='itt');const writable=canAccess(c,p.id,'_itt','write');
 async function read(files:FileList){setBusy(true);setError('');try{const all=[];for(const file of Array.from(files).slice(0,20)){const result=await extractFile(file);all.push({file,...result});}setPreview(all);}catch(e){setError((e as Error).message);}finally{setBusy(false);if(input.current)input.current.value='';}}
 async function importDocs(){setBusy(true);setError('');try{const imported:Source[]=[];for(const d of preview){const form=new FormData();form.append('file',d.file);form.append('projectId',p.id);form.append('category','itt');const res=await fetch('/api/files',{method:'POST',body:form});const data=await res.json() as {id:string;error?:string};if(!res.ok)throw new Error(data.error);imported.push({id:crypto.randomUUID(),name:d.file.name.slice(0,300),text:d.text,kind:'Tender requirement',scope:p.id,status:'needs_verification',locator:d.warning,createdAt:new Date().toISOString(),fileId:data.id,category:'itt'});}change(next=>next.sources.push(...imported));await persist();setSelectedSources(imported.map(s=>s.id));setPreview([]);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function detect(){const chosen=sources.filter(s=>!selectedSources.length||selectedSources.includes(s.id));const rows=chosen.flatMap(s=>extractQuestions(s.text).map(q=>({...q,locator:s.name+' · '+q.locator,selected:!p.questions.some(x=>x.ref.toLowerCase()===q.ref.toLowerCase()),warning:p.questions.some(x=>x.ref.toLowerCase()===q.ref.toLowerCase())?'This reference already exists. Existing answers will not be overwritten.':q.warning})));const seen=new Set<string>();setCandidates(rows.map(q=>{if(seen.has(q.ref))return {...q,selected:false,warning:'Duplicate detected reference. Select only one or change its reference.'};seen.add(q.ref);return q;}));if(!rows.length)setError('No clear question headings were detected. Use a question workbook or paste the exact question through Add question.');}
 async function importQuestions(){const chosen=candidates.filter(q=>q.selected);if(chosen.some(q=>p.questions.some(x=>x.ref.toLowerCase()===q.ref.toLowerCase())))return setError('Change or deselect duplicate question references.');if(new Set(chosen.map(q=>q.ref.toLowerCase())).size!==chosen.length)return setError('Selected question references must be unique.');
 const questions:Question[]=chosen.map(q=>({id:crypto.randomUUID(),ref:q.ref,title:q.title,text:q.text,limit:q.limit,unit:q.unit,includeSpaces:true,countHeading:false,style:'Commissioner-friendly',structure:'Flowing narrative',criteria:[],input:'',evidenceIds:[],draft:'',status:'draft',versions:[],review:[],notes:'Extracted candidate, reviewed on import. '+q.locator}));setBusy(true);try{change(next=>next.projects.find(x=>x.id===p.id)!.questions.push(...questions));await persist();setCandidates([]);if(questions[0])openQuestion(questions[0].id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="intake-page"><input className="hidden" ref={input} type="file" multiple accept=".pdf,.docx,.xlsx,.txt,.md,.csv" onChange={e=>e.target.files&&read(e.target.files)}/><section className="intake-drop model-panel"><div><FileText size={28}/><h2>Current ITT documents</h2><p>Keep the invitation, specifications, question schedules and clarifications together for this bid. Historical experience sits in its own library.</p></div><button className="btn primary" disabled={busy||!writable} onClick={()=>input.current?.click()}><Upload size={17}/>{busy?'Reading documents…':'Upload ITT documents'}</button></section>{error&&<p className="source-warning" role="alert">{error}</p>}
 <section className="model-panel"><div className="panel-title"><h2>Documents for {p.name}</h2><button className="btn" disabled={busy||!writable||!sources.length} onClick={detect}><Sparkles size={16}/>Extract question candidates</button></div><p className="hint">Select the question schedule before extraction. Confirm wording, limits and references in the preview; automated extraction never overwrites an existing answer.</p><div className="document-list">{sources.map(s=><article key={s.id}><Tick value={selectedSources.includes(s.id)} change={v=>setSelectedSources(v?[...selectedSources,s.id]:selectedSources.filter(x=>x!==s.id))} label={s.name}/><span className={'tag '+s.status}>{s.status==='approved'?'Verified':'Needs verification'}</span><details><summary>Read extracted text</summary><pre>{s.text}</pre></details><div className="bottom-actions">{s.fileId&&<a className="btn compact" href={'/api/files?id='+encodeURIComponent(s.fileId)}><Download size={14}/>Original</a>}{writable&&s.status!=='approved'&&<button className="btn compact" onClick={async()=>{change(next=>next.sources.find(x=>x.id===s.id)!.status='approved');await persist();}}><Check size={14}/>I checked the extract</button>}{c.me.role==='master'&&<DeleteAction label="Delete ITT document" confirmText={s.name} data={{action:'deleteDocument',projectId:p.id,sourceId:s.id}} perform={perform}/>}</div></article>)}{!sources.length&&<p className="empty-copy">Upload the current tender documents to start the bid briefing and question extraction.</p>}</div></section>
 <DeadlinePanel p={p} w={w} c={c} edit={edit}/><section className="model-panel"><h2>Captured questions</h2><div className="question-tracker">{p.questions.map(q=><button key={q.id} onClick={()=>openQuestion(q.id)}><span className="qref">{q.ref}</span><span><strong>{q.title}</strong><small>{q.limit?.toLocaleString()||'Confirm limit'} {q.unit}</small></span><span className={'stage '+q.status}>{q.status==='approved'?'Complete':q.status==='review'?'In review':'Draft'}</span></button>)}</div></section>
 <ReviewPanel p={p} w={w} c={c} target="_itt" perform={perform}/>
 <Dialog open={preview.length>0} onOpenChange={open=>!open&&!busy&&setPreview([])}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>Review ITT imports</DialogTitle><DialogDescription>Review the extracted text. Documents remain unverified until you check them against the originals.</DialogDescription></DialogHeader><div className="dialog-form">{preview.map((d,i)=><details key={i} open={i===0}><summary>{d.file.name} · {d.text.length.toLocaleString()} characters</summary><p className="source-warning">{d.warning}</p><textarea aria-label="ITT extract preview" rows={8} value={d.text} onChange={e=>setPreview(preview.map((x,n)=>n===i?{...x,text:e.target.value}:x))}/></details>)}<button className="btn primary" disabled={busy} onClick={importDocs}>Save {preview.length} ITT document{preview.length===1?'':'s'}</button></div></DialogContent></Dialog>
 <Dialog open={candidates.length>0} onOpenChange={open=>!open&&!busy&&setCandidates([])}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>Review extracted questions</DialogTitle><DialogDescription>Check every selected question before import. Required attachments and scoring criteria may need manual confirmation.</DialogDescription></DialogHeader><div className="dialog-form question-candidates">{candidates.map((q,i)=>{const update=(patch:Partial<QuestionCandidate>)=>setCandidates(candidates.map((x,n)=>n===i?{...x,...patch}:x));return <article key={i}><Tick value={q.selected} change={selected=>update({selected})} label={q.ref+' · '+q.title}/>{q.warning&&<p className="source-warning">{q.warning}</p>}<div className="form-pair"><label>Reference<input value={q.ref} onChange={e=>update({ref:e.target.value})}/></label><label>Title<input value={q.title} onChange={e=>update({title:e.target.value})}/></label></div><label>Exact question<textarea value={q.text} rows={5} onChange={e=>update({text:e.target.value})}/></label><div className="form-pair"><label>Maximum<input type="number" min={1} max={100000} value={q.limit??''} onChange={e=>update({limit:e.target.value?Number(e.target.value):null})}/></label><label>Unit<Pick label="Extracted question count unit" value={q.unit} change={unit=>update({unit:unit as QuestionCandidate['unit']})} items={[{value:'characters',label:'Characters'},{value:'words',label:'Words'}]}/></label></div><span className="hint">{q.locator}</span></article>;})}{error&&<p className="source-warning">{error}</p>}<button className="btn primary" disabled={busy||!candidates.some(q=>q.selected)} onClick={importQuestions}>Import {candidates.filter(q=>q.selected).length} reviewed questions</button></div></DialogContent></Dialog>
 </div>;
}
export function BriefPanel({p,w,c,edit,perform}:{p:Project;w:Workspace;c:Collaboration;edit:(patch:Partial<Project>)=>void;perform:Perform}){
 const brief=p.brief||buildBrief(p,w.sources);const write=canAccess(c,p.id,'_brief','write');const [mode,setMode]=useState('all');const gaps=brief.gaps.filter(g=>mode==='all'||g.state!== 'confirmed');
 return <div className="brief-page"><section className="model-panel"><div className="panel-title"><div><span className="eyebrow">BID BRIEFING</span><h2>Scope, requirements and suggested inputs</h2></div><button className="btn" disabled={!write} onClick={()=>edit({brief:buildBrief(p,w.sources)})}>Refresh suggestions</button></div><p className="hint">This briefing is assembled from the current question list and detected ITT extracts. Verify dates, financial limits and requirements in the original tender.</p><fieldset disabled={!write}><label>Bid summary<textarea rows={4} value={brief.summary} onChange={e=>edit({brief:{...brief,summary:e.target.value}})}/></label><div className="brief-facts">{[['deadline','Submission deadline'],['contractTerm','Contract term / mobilisation'],['budget','Financial envelope']].map(([key,label])=><label key={key}>{label}<textarea rows={3} value={brief[key as 'deadline'|'contractTerm'|'budget']} onChange={e=>edit({brief:{...brief,[key]:e.target.value}})}/></label>)}</div></fieldset><div className="requirement-excerpts">{brief.requirements.map(r=><details key={r.id}><summary>{r.title} · {w.sources.find(s=>s.id===r.sourceId)?.name}</summary><p>{r.excerpt}</p></details>)}</div></section>
 <section className="model-panel"><div className="panel-title"><h2>Data needed to strengthen the bid</h2><Pick label="Data gap filter" value={mode} change={setMode} items={[{value:'all',label:'All inputs'},{value:'open',label:'Outstanding inputs'}]}/></div><div className="data-gaps">{gaps.map(g=>{const update=(patch:Partial<typeof g>)=>edit({brief:{...brief,gaps:brief.gaps.map(x=>x.id===g.id?{...x,...patch}:x)}});return <article key={g.id}><header><span className={'tag '+(g.state==='confirmed'?'approved':g.priority==='high'?'needs_verification':'pale')}>{g.state==='confirmed'?'Confirmed':g.priority==='high'?'Key input':'Strengthen'}</span><h3>{g.title}</h3></header><p>{g.detail}</p><fieldset disabled={!write}><div className="form-three"><label>Status<Pick label="Data gap status" value={g.state} change={state=>update({state:state as typeof g.state})} items={[{value:'open',label:'Open'},{value:'in_progress',label:'In progress'},{value:'confirmed',label:'Confirmed with evidence'}]}/></label><label>Owner<Pick label="Data gap owner" value={g.ownerId} change={ownerId=>update({ownerId})} items={[{value:'',label:'Unassigned'},...c.members.filter(m=>m.active).map(m=>({value:m.id,label:m.name}))]}/></label><label>Due<input type="date" value={g.dueDate} onChange={e=>update({dueDate:e.target.value})}/></label></div><label>Evidence / confirmed input<textarea rows={2} value={g.evidence} onChange={e=>update({evidence:e.target.value})} placeholder="Record the value, source and date; attach the source in the relevant section."/></label></fieldset></article>;})}</div><button className="btn" onClick={()=>download(JSON.stringify(brief,null,2),'DRPA-bid-brief-and-data.json','application/json')}><Download size={16}/>Export briefing and data list</button></section><ReviewPanel p={p} w={w} c={c} target="_brief" perform={perform}/></div>;
}
