import {CheckCircle2,FileText,Calculator,Users,ArrowRight,Download} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import type {Project,Workspace,Collaboration} from '@/lib/types';
import {completion,responseCountSafe} from '@/lib/overview-utils';
import {canAccess} from '@/lib/finance';
import {exportPack,download} from '@/lib/files';
import {when} from './shared';
import {Countdown,DeadlinePanel,BidActions} from './lifecycle';
import type {Perform} from './collaboration';
export function Overview({p,w,c,open,edit,perform}:{p:Project;w:Workspace;c:Collaboration;open:(page:string,qid?:string)=>void;edit:(patch:Partial<Project>)=>void;perform:Perform}){
 const progress=c.progress?.[p.id]||completion(p,w.sources,c.comments);const unanswered=p.questions.filter(q=>!q.draft.trim()).length;const comments=c.comments.filter(x=>x.projectId===p.id&&(x.status==='open'||x.status==='accepted'&&!x.applied));
 return <div className="overview-page"><section className="bid-progress"><div><span className="eyebrow">{p.commissioner||'COMMISSIONER'}</span><h2>{p.name}</h2><p>{p.scope}</p></div><div className="progress-total"><strong>{progress.percent}%</strong><span>complete</span></div><Progress value={progress.percent} aria-label="Whole bid completion"/><div className="progress-legend"><span>{progress.answers} / {progress.total-4} answers complete</span><span>ITT documents {progress.itt?'complete':'pending'}</span><span>Key data {progress.brief?'complete':'pending'}</span><span>Service model {progress.model?'complete':'pending'}</span><span>FMT {progress.fmt?'complete':'pending'}</span></div></section>
 <Countdown p={p}/><div className="stat-grid"><article><span>Assigned answers</span><strong>{p.questions.length}</strong><small>{unanswered} without a draft</small></article><article><span>Awaiting review</span><strong>{p.questions.filter(q=>q.status==='review').length}</strong><small>Checker sign-off required</small></article><article><span>Unresolved comments</span><strong>{comments.length}</strong><small>Decisions and incorporation</small></article><article><span>Key data gaps</span><strong>{p.brief?.gaps.filter(g=>g.state!=='confirmed').length||0}</strong><small>From ITT and bid requirements</small></article></div>
 <section className="model-panel"><div className="panel-title"><div><h2>Bid workspace</h2><p>Start with the current ITT, build the service and cost model, then draft and review each answer.</p></div><button className="btn" onClick={()=>exportPack(p.questions,w,c)}><Download size={16}/>Export review pack</button></div><div className="workspace-tiles">{[{page:'intake',target:'_itt',icon:FileText,title:'ITT documents and questions',body:'Upload, extract, verify and organise the current tender.'},{page:'brief',target:'_brief',icon:CheckCircle2,title:'Bid briefing and data',body:'Scope, requirements, suggested evidence and missing inputs.'},{page:'model',target:'_model',icon:Users,title:'Service model and TUPE',body:'Pathways, staffing capacity, transferred staff and non-pay costs.'},{page:'fmt',target:'_fmt',icon:Calculator,title:'Financial model / FMT',body:'Map costs to the commissioner workbook and export for review.'}].filter(t=>canAccess(c,p.id,t.target)).map(t=><button key={t.page} onClick={()=>open(t.page)}><t.icon size={24}/><strong>{t.title}</strong><span>{t.body}</span></button>)}</div></section>
 <section className="model-panel"><div className="panel-title"><h2>{c.me.role==='master'?'Questions':'Your assigned questions'}</h2><button className="text-btn" onClick={()=>open('team')}>Users and assignments</button></div><div className="question-tracker">{p.questions.map(q=><button key={q.id} onClick={()=>open('studio',q.id)}><span className="qref">{q.ref}</span><span><strong>{q.title}</strong><small>{responseCountSafe(q).toLocaleString()} / {q.limit?.toLocaleString()||'Limit missing'} {q.unit}</small></span><span className={'stage '+q.status}>{q.status==='approved'?'Complete':q.status==='review'?'In review':q.draft?'Draft':'Not started'}</span><span className="tracker-comments">{comments.filter(x=>x.targetId===q.id).length} comments</span></button>)}</div>{!p.questions.length&&<p className="empty-copy">No questions assigned yet. You can still use your assigned sections.</p>}</section>
 {canAccess(c,p.id,'_itt')&&<DeadlinePanel p={p} w={w} c={c} edit={edit}/>}<BidActions p={p} c={c} perform={perform}/><section className="model-panel"><h2>Next actions</h2><div className="next-actions">{!w.sources.some(s=>s.scope===p.id&&s.category==='itt')&&<p>Upload the current ITT and specifications.</p>}{unanswered>0&&<p>Prepare {unanswered} first draft{unanswered===1?'':'s'}.</p>}{comments.length>0&&<p>Resolve {comments.length} comment{comments.length===1?'':'s'} before approval.</p>}{!progress.model&&<p>Complete and check the service model, including TUPE assumptions.</p>}{!progress.fmt&&<p>Map, export, recalculate and sign off the financial model.</p>}</div></section></div>;
}
