import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
export function Pick({value,change,items,label,disabled=false}:{value:string;change:(s:string)=>void;items:{value:string;label:string}[];label:string;disabled?:boolean}){return <Select value={value||'__blank'} onValueChange={v=>change(v==='__blank'?'':v)} disabled={disabled}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value||'__blank'} value={i.value||'__blank'}>{i.label}</SelectItem>)}</SelectContent></Select>;}
export function Tick({value,change,label,disabled=false}:{value:boolean;change:(v:boolean)=>void;label:string;disabled?:boolean}){return <label className="toggle"><Checkbox checked={value} onCheckedChange={v=>change(v===true)} disabled={disabled}/><span>{label}</span></label>;}
export const money=(n:number|null)=>n===null?'Missing input':new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n);
export const number=(n:number|null,digits=3)=>n===null?'Missing input':n.toLocaleString('en-GB',{maximumFractionDigits:digits});
export const when=(s:string)=>new Date(s).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
export function Numeric({value,change,label,max=1e10,min=0}:{value:number|null;change:(n:number|null)=>void;label:string;max?:number;min?:number}){return <input aria-label={label} type="number" step="any" min={min} max={max} value={value??''} placeholder="Confirm" onChange={e=>change(e.target.value===''?null:Number(e.target.value))}/>;}
export function csv(rows:(string|number|null)[][]){return rows.map(row=>row.map(value=>{if(value===null)return '"Missing input"';const text=typeof value==='number'?String(value):/^[=+@\-\t\r]/.test(value)?"'"+value:value;return '"'+text.replace(/"/g,'""')+'"';}).join(',')).join('\r\n');}
