import {ApiError,db,failed,json,runtime} from '@/lib/server';
import {context,loadShared,requireAccess,targetProject,writeShared,SHARED_KEY} from '@/lib/collaboration';
import {hashBytes,contentHash,targetContent,fmtIssues} from '@/lib/finance';
import {readWorkbook,validateMappings,fillFMT,completedWorkbookFacts} from '@/lib/xlsx';
export async function POST(request:Request){try{
 const c=await context(request,true);const b=await request.json() as any;const state=await loadShared(c);const p=targetProject(state.workspace,b.projectId,'_fmt');requireAccess(c,p.id,'_fmt','write');
 if(!p.fmt?.fileId||p.fmt.mode!=='completed'&&!p.serviceModel)throw new ApiError(400,'Upload the FMT and build the service model, or choose an externally completed FMT.');const problems=fmtIssues(p);if(problems.length)throw new ApiError(400,problems.slice(0,8).join('\n'));
 const record=await db().prepare('SELECT * FROM files WHERE id=?').bind(p.fmt.fileId).first<any>();if(!record||record.category!=='financial'||record.project_id!==p.id)throw new ApiError(400,'The FMT must be a financial workbook uploaded for this bid.');const object=await runtime().BUCKET?.get(`${record.owner_id}/${record.id}`);if(!object)throw new ApiError(404,'FMT original file unavailable.');const bytes=new Uint8Array(await object.arrayBuffer());
 if(await hashBytes(bytes)!==p.fmt.fingerprint)throw new ApiError(409,'The workbook fingerprint changed. Upload and map the correct original again.');const workbook=readWorkbook(bytes);const errors=p.fmt.mode==='completed'?[]:validateMappings(workbook,p.serviceModel!,p.fmt);if(p.fmt.mode==='completed')completedWorkbookFacts(workbook,p.fmt);if(errors.length)throw new ApiError(400,errors.slice(0,8).join('\n'));
 const hash=await contentHash(targetContent(p,'_fmt',state.workspace));p.fmt.validatedHash=hash;p.fmt.validationNote=p.fmt.mode==='completed'?'Selected summary cells read from the uploaded completed workbook. Saved formula values require a recorded Excel recalculation and summary review.':'Numeric input mappings validated against the original workbook; formula, locked and merged targets excluded.';
 let output:Uint8Array|undefined;let outputId:string|null=null;if(b.action==='export'){output=p.fmt.mode==='completed'?bytes:fillFMT(bytes,p.serviceModel!,p.fmt);p.fmt.exportedHash=hash;outputId=crypto.randomUUID();p.fmt.outputFileId=outputId;await runtime().BUCKET!.put(`${SHARED_KEY}/${outputId}`,output);}else if(b.action!=='validate')throw new ApiError(400,'Choose validate or export.');
 let result;try{result=await writeShared(c,state.workspace,b.revision,b.action==='export'?'Exported costed FMT':'Validated FMT mapping',p.id,'_fmt',mutation=>outputId?[db().prepare('INSERT INTO files (id,owner_id,name,size,mime,created_at,project_id,category,target_id) SELECT ?,?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM workspaces WHERE owner_id=? AND mutation_id=?)').bind(outputId,SHARED_KEY,'DRPA-costed-FMT-RECALCULATE.xlsx',output!.byteLength,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',new Date().toISOString(),p.id,'financial','_fmt',SHARED_KEY,mutation)]:[]);}catch(e){if(outputId)await runtime().BUCKET!.delete(`${SHARED_KEY}/${outputId}`);throw e;}
 if(output)return new Response(output.slice().buffer,{headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':"attachment; filename*=UTF-8''DRPA-costed-FMT-RECALCULATE.xlsx",'Cache-Control':'no-store','X-Workspace-Revision':String(result.revision)}});return json({...result,hash,note:p.fmt.validationNote});
}catch(e){return failed(e);}}
