import {z} from 'zod';
import {context,loadShared,writeShared,invalidateChanged} from '@/lib/collaboration';
import {runtime,failed,json,ApiError} from '@/lib/server';
import {contentHash} from '@/lib/finance';
import type {Source} from '@/lib/types';
const row=z.object({id:z.string().min(1).max(200),metric:z.string().max(100),title:z.string().max(300),site:z.string().max(300),period:z.string().regex(/^20\d{2}-(0[1-9]|1[0-2])$/),numerator:z.number().finite().min(0).max(1e15),denominator:z.number().finite().min(0).max(1e15),numeratorLabel:z.string().max(300),denominatorLabel:z.string().max(300),method:z.enum(['ratio','sum','mean','rate','value']),unit:z.string().max(80),value:z.number().finite().max(1e15),source:z.string().min(1).max(2000),observationVersion:z.string().max(100),definitionVersion:z.string().max(100),updatedAt:z.string().max(100)});
const schema=z.object({schemaVersion:z.literal(1),published:z.boolean(),complete:z.literal(true),configurationVersion:z.string().max(100),records:z.array(row).max(40)});
const configured=()=>!!(runtime().INTELLIGENCE_FEED_URL&&runtime().INTELLIGENCE_FEED_KEY);
export async function GET(request:Request){try{const c=await context(request);if(c.me.role!=='master')throw new ApiError(403,'Only master users manage evidence feeds.');return json({configured:configured(),source:'DRPA Intelligence',configurationUrl:'https://drpa-intelligence-engine.sa33dc.chatgpt.site/bid-evidence'});}catch(e){return failed(e);}}
export async function POST(request:Request){try{const c=await context(request,true);if(c.me.role!=='master')throw new ApiError(403,'Only master users can synchronise reusable evidence.');if(!configured())throw new ApiError(503,'The server evidence-feed connection has not been configured.');const body=await request.json() as any,state=await loadShared(c),before=structuredClone(state.workspace);const address=new URL(runtime().INTELLIGENCE_FEED_URL!);if(address.protocol!=='https:'||address.pathname!=='/api/bid-evidence'||address.search||address.username||address.password)throw new ApiError(503,'Configure the exact HTTPS Intelligence bid-evidence endpoint on the server.');const headers:Record<string,string>={Authorization:'Bearer '+runtime().INTELLIGENCE_FEED_KEY!};if(runtime().INTELLIGENCE_SITES_TOKEN)headers['OAI-Sites-Authorization']='Bearer '+runtime().INTELLIGENCE_SITES_TOKEN;const response=await fetch(address.toString(),{headers,redirect:'manual',signal:AbortSignal.timeout(12000)});if(response.status>=300&&response.status<400)throw new ApiError(502,'The Intelligence feed redirected. Configure its exact endpoint; credentials were not forwarded.');const raw=await boundedText(response);let parsed:any;try{parsed=JSON.parse(raw);}catch{throw new ApiError(502,'The private Intelligence feed did not return its evidence format.');}if(!response.ok)throw new ApiError(502,String(parsed.error||'Intelligence feed unavailable.').slice(0,1500));const result=schema.safeParse(parsed);if(!result.success)throw new ApiError(502,'The Intelligence feed failed validation. No evidence was imported.');const feed=result.data;const seen=new Set<string>();let added=0,updated=0;
 for(const r of feed.records){if(seen.has(r.id))throw new ApiError(502,'The Intelligence feed returned duplicate records.');seen.add(r.id);if(['ratio','mean','rate'].includes(r.method)&&r.denominator<=0)throw new ApiError(502,'A feed record is missing its denominator.');const calculated=r.method==='value'||r.method==='sum'?r.numerator:r.numerator/r.denominator*(r.method==='ratio'?100:r.method==='rate'?1000:1);if(Math.abs(calculated-r.value)>Math.max(1e-8,Math.abs(calculated)*1e-10))throw new ApiError(502,'A feed calculation does not match its source counts.');const id='intel-'+(await contentHash(r.id)).slice(0,40),old=state.workspace.sources.find(s=>s.id===id),version=r.observationVersion+' / '+r.definitionVersion+' / feed '+feed.configurationVersion;const text=`${r.title}\nSite: ${r.site}\nPeriod: ${r.period}\nValue: ${r.value} ${r.unit}\n${r.numeratorLabel}: ${r.numerator}\n${r.denominatorLabel}: ${r.denominator}\nMethod: ${r.method}\nSource reference: ${r.source}\nObservation version: ${r.observationVersion}; definition: ${r.definitionVersion}\nApproved source record updated: ${r.updatedAt}`;if(old?.origin?.version===version&&old.text===text)continue;const source:Source={id,name:(r.title+' · '+r.site+' · '+r.period).slice(0,300),text,kind:'Approved aggregate performance',scope:'global',status:'needs_verification',locator:(address.origin+' · '+r.source).slice(0,2000),createdAt:old?.createdAt||new Date().toISOString(),category:'intelligence',visibility:'master',origin:{kind:'intelligence',recordId:r.id,period:r.period,version,retrievedAt:new Date().toISOString(),projectId:'drpa'}};if(old){state.workspace.sources[state.workspace.sources.indexOf(old)]=source;updated++;}else {state.workspace.sources.push(source);added++;}}
 // Withdrawn or unpublished records cannot continue to support new drafts.
 let withdrawn=0;for(const source of state.workspace.sources.filter(s=>s.origin?.kind==='intelligence'&&s.origin.projectId==='drpa'))if(!seen.has(source.origin!.recordId)&&source.status==='approved'){source.status='needs_verification';source.visibility='master';source.locator=('Record no longer published in the current Intelligence feed. '+source.locator).slice(0,2000);withdrawn++;}
 if(state.workspace.sources.length>60)throw new ApiError(400,'The evidence library would exceed 60 extracts. Narrow the feed or remove older extracts before synchronising.');invalidateChanged(before,state.workspace);const saved=await writeShared(c,state.workspace,body.revision,'Synchronised DRPA Intelligence feed');return json({...saved,published:feed.published,added,updated,withdrawn,message:feed.published?`${added} new and ${updated} changed extracts await master verification; ${withdrawn} withdrawn.`:'The Intelligence master has not published a scope. No new records were imported.'});}catch(e){return failed(e);}}

async function boundedText(response:Response){if(!response.body)return '';const reader=response.body.getReader(),decoder=new TextDecoder();let size=0,text='';try{while(true){const chunk=await reader.read();if(chunk.done)break;size+=chunk.value.byteLength;if(size>250000){await reader.cancel();throw new ApiError(502,'The evidence-feed response exceeded its size limit.');}text+=decoder.decode(chunk.value,{stream:true});}return text+decoder.decode();}finally{reader.releaseLock();}}
