import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import fs from 'node:fs/promises';
import {createRuntime,identity} from './test-runtime.mjs';
import {demoModel,demoFMT,demoMappings} from './demo-fixture.mjs';
const origin='https://workbench.test';const master='master@example.test',writer='writer@example.test',checker='checker@example.test';
const mf=await createRuntime();
async function request(email,path,body,expected=200){const r=await mf.dispatchFetch(origin+path,{method:body?'POST':'GET',headers:{...identity(email),...(body?{Origin:origin,'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const raw=await r.text();assert.equal(r.status,expected,`${path} ${raw.slice(0,900)}`);return raw?JSON.parse(raw):null;}
const state=email=>request(email,'/api/workspace');
async function action(email,path,data,expected=200){const s=await state(master);return request(email,path,{...data,revision:s.revision},expected);}
async function put(email,workspace,revision,expected=200){const r=await mf.dispatchFetch(origin+'/api/workspace',{method:'PUT',headers:{...identity(email),Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({workspace,revision})});const raw=await r.text();assert.equal(r.status,expected,raw.slice(0,900));return JSON.parse(raw);}
async function upload(name,bytes,category){const boundary='fixture-upload';const body=Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="projectId"\r\n\r\nwinchester\r\n--${boundary}\r\nContent-Disposition: form-data; name="category"\r\n\r\n${category}\r\n--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="${name}"\r\nContent-Type: application/octet-stream\r\n\r\n`),Buffer.from(bytes),Buffer.from(`\r\n--${boundary}--\r\n`)]);const r=await mf.dispatchFetch(origin+'/api/files',{method:'POST',headers:{...identity(master),Origin:origin,'Content-Type':`multipart/form-data; boundary=${boundary}`},body});const data=await r.json();assert.equal(r.status,200,JSON.stringify(data));return data.id;}
try{
 let r=await mf.dispatchFetch(origin+'/api/workspace');assert.equal(r.status,401);await r.text();await request('uninvited@example.test','/api/workspace',null,403);
 let badOrigin=await mf.dispatchFetch(origin+'/api/workspace',{method:'PUT',headers:{...identity(master),'Content-Type':'application/json'},body:'{}'});assert.equal(badOrigin.status,403);await badOrigin.text();
 let s=await state(master);assert.equal(s.collaboration.me.role,'master');assert.equal(s.workspace.projects[0].questions.length,3);
 for(const [email,name,role] of [[writer,'Test Writer','writer'],[checker,'Test Checker','checker']])await action(master,'/api/team',{action:'member',member:{email,name,role,active:true}});
 s=await state(master);const writerId=s.collaboration.members.find(m=>m.email===writer).id,checkerId=s.collaboration.members.find(m=>m.email===checker).id;
 for(const [memberId,access] of [[writerId,'write'],[checkerId,'check']])await action(master,'/api/team',{action:'assign',projectId:'winchester',targetId:'q01',memberId,access});
 s=await state(master);s.workspace.sources.push({id:'private-finance',name:'Private finance fixture',text:'SECRET-FINANCE',kind:'Financial model',scope:'winchester',status:'needs_verification',locator:'Synthetic private fixture',createdAt:new Date().toISOString(),category:'financial'});s.workspace.sources.push({id:'private-tupe',name:'Private workforce fixture',text:'SECRET-TUPE',kind:'Workforce evidence',scope:'winchester',status:'needs_verification',locator:'Synthetic private fixture',createdAt:new Date().toISOString(),category:'tupe'});await put(master,s.workspace,s.revision);
 let ws=await state(writer);assert.equal(ws.workspace.projects[0].questions.length,1);assert.equal(ws.workspace.projects[0].serviceModel,undefined);assert.ok(!JSON.stringify(ws).includes('SECRET-FINANCE'));assert.ok(!JSON.stringify(ws).includes('SECRET-TUPE'));
 await action(checker,'/api/comments',{action:'add',projectId:'winchester',targetId:'q02',text:'Unauthorized comment',quote:'',proposal:''},403);
 await action(writer,'/api/team',{action:'member',member:{email:'bad@example.test',name:'Bad','role':'master',active:true}},403);
 await put(checker,(await state(checker)).workspace,(await state(checker)).revision,403);
 const tuitionFile=await upload('private-test.txt',Buffer.from('PRIVATE-STAFF-DETAILS'),'tupe');r=await mf.dispatchFetch(origin+'/api/files?id='+tuitionFile,{headers:identity(checker)});assert.equal(r.status,404);await r.text();
 ws=await state(writer);ws.workspace.projects[0].questions[0].draft='Our clinical team reviews care and escalates risks through clear governance.';ws.workspace.projects[0].questions[0].text='Describe the service and governance.';ws.workspace.projects[0].questions[0].limit=1000;const stale=ws.revision;await put(writer,ws.workspace,ws.revision);await put(writer,ws.workspace,stale,409);
 ws=await state(writer);ws.workspace.projects[0].questions[0].status='approved';await put(writer,ws.workspace,ws.revision,400);
 await action(checker,'/api/comments',{action:'add',projectId:'winchester',targetId:'q01',text:'Make ownership clearer.',quote:'Our clinical team',proposal:'Our accountable clinical team'});
 s=await state(master);let comment=s.collaboration.comments.find(c=>c.targetId==='q01');await action(checker,'/api/comments',{action:'decide',projectId:'winchester',targetId:'q01',id:comment.id,decision:'accepted',note:''},403);
 await action(writer,'/api/comments',{action:'decide',projectId:'winchester',targetId:'q01',id:comment.id,decision:'accepted',note:'Applied exact wording suggestion.'});assert.match((await state(writer)).workspace.projects[0].questions[0].draft,/accountable clinical team/);
 for(const targetId of ['_model','_fmt'])for(const [memberId,access] of [[writerId,'write'],[checkerId,'check']])await action(master,'/api/team',{action:'assign',projectId:'winchester',targetId,memberId,access});
 const template=demoFMT(),fileId=await upload('demo-template.xlsx',template,'financial');s=await state(master);const p=s.workspace.projects[0];p.serviceModel=demoModel();p.fmt={fileId,name:'demo-template.xlsx',fingerprint:createHash('sha256').update(template).digest('hex'),sheets:[{name:'Inputs',rows:4,columns:7}],mappings:demoMappings(),status:'draft',validatedHash:'',validationNote:'',exportedHash:''};await put(master,s.workspace,s.revision);
 await action(writer,'/api/workflow',{action:'check',projectId:'winchester',targetId:'_model'},403);await action(writer,'/api/workflow',{action:'submit',projectId:'winchester',targetId:'_model'});await action(checker,'/api/workflow',{action:'check',projectId:'winchester',targetId:'_model'});await action(master,'/api/workflow',{action:'approve',projectId:'winchester',targetId:'_model'});
 s=await state(master);s.workspace.projects[0].fmt.mappings[0].cell='F1';await put(master,s.workspace,s.revision);await action(master,'/api/fmt',{action:'validate',projectId:'winchester'},400);s=await state(master);s.workspace.projects[0].fmt.mappings=demoMappings();await put(master,s.workspace,s.revision);
 await action(master,'/api/fmt',{action:'validate',projectId:'winchester'});s=await state(master);r=await mf.dispatchFetch(origin+'/api/fmt',{method:'POST',headers:{...identity(master),Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({action:'export',projectId:'winchester',revision:s.revision})});assert.equal(r.status,200,await (r.status!==200?r.text():Promise.resolve('')));const costed=new Uint8Array(await r.arrayBuffer());await fs.writeFile('work/server-costed-FMT.xlsx',costed);
 await action(checker,'/api/workflow',{action:'check',projectId:'winchester',targetId:'_fmt'});await action(master,'/api/workflow',{action:'approve',projectId:'winchester',targetId:'_fmt',confirmRecalculated:false,note:'No check'},400);await action(master,'/api/workflow',{action:'approve',projectId:'winchester',targetId:'_fmt',confirmRecalculated:true,note:'Synthetic fixture totals reconciled independently: price 132990.'});
 await action(checker,'/api/workflow',{action:'check',projectId:'winchester',targetId:'q01'});await action(master,'/api/workflow',{action:'approve',projectId:'winchester',targetId:'q01'});assert.equal((await state(master)).workspace.projects[0].questions[0].status,'approved');
 await action(checker,'/api/comments',{action:'add',projectId:'winchester',targetId:'q01',text:'Confirm the escalation owner in the review record.',quote:'',proposal:''});s=await state(master);comment=s.collaboration.comments.find(c=>c.status==='open'&&c.targetId==='q01');await action(master,'/api/workflow',{action:'approve',projectId:'winchester',targetId:'q01'},400);
 await action(writer,'/api/comments',{action:'decide',projectId:'winchester',targetId:'q01',id:comment.id,decision:'accepted',note:'Will confirm owner.'});await action(checker,'/api/workflow',{action:'check',projectId:'winchester',targetId:'q01'},400);await action(writer,'/api/comments',{action:'incorporate',projectId:'winchester',targetId:'q01',id:comment.id,note:'Synthetic owner confirmed and included in the review record.'});await action(master,'/api/workflow',{action:'approve',projectId:'winchester',targetId:'q01'},400);await action(checker,'/api/workflow',{action:'check',projectId:'winchester',targetId:'q01'});await action(master,'/api/workflow',{action:'approve',projectId:'winchester',targetId:'q01'});
 s=await state(checker);assert.ok(s.collaboration.targetHashes['winchester:q01']);assert.ok(s.collaboration.checks.some(c=>c.targetId==='q01'&&c.contentHash===s.collaboration.targetHashes['winchester:q01']));
 ws=await state(writer);ws.workspace.projects[0].questions[0].draft+=' The reviewed pathway is documented.';await put(writer,ws.workspace,ws.revision);assert.equal((await state(master)).workspace.projects[0].questions[0].status,'draft');await action(master,'/api/workflow',{action:'approve',projectId:'winchester',targetId:'q01'},400);
 s=await state(master);s.workspace.projects[0].serviceModel.staff[0].salaryFte=41000;await put(master,s.workspace,s.revision);s=await state(master);assert.equal(s.workspace.projects[0].serviceModel.status,'draft');assert.equal(s.workspace.projects[0].fmt.status,'draft');assert.equal(s.workspace.projects[0].fmt.validatedHash,'');assert.equal(s.workspace.projects[0].modelSourceId,null);assert.equal(s.workspace.projects[0].facts.length,0);
 await action(master,'/api/team',{action:'member',member:{id:writerId,email:writer,name:'Test Writer',role:'writer',active:false}});await request(writer,'/api/workspace',null,403);
 r=await mf.dispatchFetch(origin+'/',{headers:identity(master)});assert.equal(r.status,200);assert.match(await r.text(),/DRPA Bid Workbench/);
 console.log('PASS: anonymous/uninvited denial; shared persistence; assigned-only visibility/comments; role restrictions; finance/TUPE file privacy; stale-write protection; exact suggested edits; server FMT provenance; guarded export; mandatory checker and recalculation sign-off; current-comment review hashes; approval invalidation; revoked users; root rendering.');
}finally{await mf.dispose();}
const secure=await createRuntime({bindings:{AUTH_MODE:'cloudflare-access',ACCESS_TEAM_DOMAIN:'https://testteam.cloudflareaccess.com',ACCESS_AUD:'test-aud'}});try{const r=await secure.dispatchFetch(origin+'/api/workspace',{headers:identity(master)});assert.equal(r.status,401);await r.text();console.log('PASS: portable authentication rejects forged Sites identity headers.');}finally{await secure.dispose();}
