import {zipSync,strToU8} from 'fflate';
export function demoFMT(){const files={
 '[Content_Types].xml':'<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>',
 '_rels/.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
 'xl/workbook.xml':'<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Inputs" sheetId="1" r:id="rId1"/></sheets><calcPr calcMode="auto"/></workbook>',
 'xl/_rels/workbook.xml.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
 'xl/styles.xml':'<?xml version="1.0"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="1"><font><sz val="11"/><name val="Arial"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyProtection="1"><protection locked="0"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyProtection="1"><protection locked="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>',
 'xl/worksheets/sheet1.xml':'<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:H4"/><sheetViews><sheetView workbookViewId="0"/></sheetViews><sheetFormatPr defaultRowHeight="15"/><sheetData><row r="1"><c r="A1" s="0"><v>0</v></c><c r="B1" s="0"><v>0</v></c><c r="C1" s="0"><v>0</v></c><c r="D1" s="0"><v>0</v></c><c r="E1" s="0"><v>0</v></c><c r="F1" s="1"><f>SUM(B1,C1:C2,D1,E1)</f><v>999</v></c><c r="G1" s="1"><v>123</v></c></row><row r="2"><c r="C2" s="0"><v>0</v></c></row><row r="3"><c r="A3" s="1" t="inlineStr"><is><t>Synthetic test workbook. Not a commissioner FMT.</t></is></c></row><row r="4"><c r="A4" s="0"><v>0</v></c></row></sheetData><sheetProtection sheet="1" objects="1" scenarios="1"/><mergeCells count="1"><mergeCell ref="A4:B4"/></mergeCells></worksheet>'
};return zipSync(Object.fromEntries(Object.entries(files).map(([k,v])=>[k,strToU8(v)])));}
export function demoModel(){return {narrative:'Synthetic integrated healthcare staffing model for software tests. Figures are illustrative.',pathways:[],staff:[{id:'staff-nurse',service:'Primary care',role:'Nurse',provider:'Test provider',grade:'Test grade',basis:'wte',wte:2,weeklyCoverage:null,fteHoursWeek:37.5,productiveWeeks:46,salaryFte:40000,allowanceFte:0,niPct:10,niThreshold:5000,pensionPct:5,otherFte:0,escalationPct:0}],tupe:[{id:'transfer-one',reference:'EMP-001',role:'Nurse',staffLineId:'staff-nurse',fte:1,salaryFte:45000,allowanceAnnual:0,niPct:10,niThreshold:5000,pensionPct:5,otherAnnual:0,include:true,verified:true,notes:'Synthetic employee, no real individual.'}],nonPay:[{id:'np-recurring',label:'Synthetic recurring cost',kind:'recurring',amount:3000,escalationPct:0,capitalTreatment:'year1',amortisationYears:null},{id:'np-mob',label:'Synthetic mobilisation cost',kind:'mobilisation',amount:1000,escalationPct:0,capitalTreatment:'year1',amortisationYears:null}],contractYears:1,weeksPerYear:52.14,tupeAssumption:'provided',overheadPct:10,profitPct:20,pricingMethod:'markup',annualBudget:150000,status:'draft',assumptions:'All values, including employer rates, are synthetic software fixtures and must not be used for a live bid.'};}
export const demoMappings=()=>[['staff_wte','staff-nurse','A1'],['staff_cost','staff-nurse','B1'],['nonpay_cost','np-recurring','C1'],['nonpay_cost','np-mob','C2'],['overhead','','D1'],['profit','','E1']].map(([metric,lineId,cell],i)=>({id:'map-'+i,metric,lineId,year:1,sheet:'Inputs',cell,verified:true}));
