import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {createRuntime,identity} from './test-runtime.mjs';
import {demoFMT} from './demo-fixture.mjs';
const origin='https://workbench.test',master='master@example.test',writer='writer@example.test',checker='checker@example.test';const mf=await createRuntime();
async function req(email,path,body,expected=200,method=body?'POST':'GET'){const r=await mf.dispatchFetch(origin+path,{method,headers:{...identity(email),...(body?{Origin:origin,'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const raw=await r.text();assert.equal(r.status,expected,path+' '+raw.slice(0,700));return raw?JSON.parse(raw):null;}
const state=()=>req(master,'/api/workspace');async function act(email,path,body,expected=200){const s=await state();return req(email,path,{...body,revision:s.revision},expected);}const put=async s=>req(master,'/api/workspace',{workspace:s.workspace,revision:s.revision},200,'PUT');
async function upload(name,bytes,category,email=master,expected=200){const boundary='lifecycle-fixture';const body=Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="projectId"\r\n\r\nwinchester\r\n--${boundary}\r\nContent-Disposition: form-data; name="category"\r\n\r\n${category}\r\n--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="${name}"\r\nContent-Type: application/octet-stream\r\n\r\n`),Buffer.from(bytes),Buffer.from(`\r\n--${boundary}--\r\n`)]);const r=await mf.dispatchFetch(origin+'/api/files',{method:'POST',headers:{...identity(email),Origin:origin,'Content-Type':`multipart/form-data; boundary=${boundary}`},body});const d=await r.json();assert.equal(r.status,expected,JSON.stringify(d));return d.id;}
try{let s=await state();for(const [email,role] of [[writer,'writer'],[checker,'checker']])await act(master,'/api/team',{action:'member',member:{email,name:role,role,active:true}});s=await state();const memberId=s.collaboration.members.find(m=>m.email===writer).id;for(const targetId of ['q01','_itt','_fmt'])await act(master,'/api/team',{action:'assign',projectId:'winchester',targetId,memberId,access:'write'});
 await act(writer,'/api/bids',{action:'deleteBid',projectId:'winchester',confirm:s.workspace.projects[0].name},403);await req(checker,'/api/bids',null,403);await req(writer,'/api/post-bid?projectId=winchester',null,403);await req(writer,'/api/evidence-feed',null,403);await upload('staff.xlsx',demoFMT(),'staffing',checker,403);await upload('final.txt',Buffer.from('Finished bid'),'completed',writer,403);
 let ws=await req(writer,'/api/workspace');ws.workspace.sources.push({id:'forged-evidence',name:'Forged',text:'Not a master feed',kind:'Previous response',scope:'winchester',status:'approved',locator:'',createdAt:'',category:'historic'});await req(writer,'/api/workspace',{workspace:ws.workspace,revision:ws.revision},403,'PUT');
 s=await state();const externalId=await upload('completed.xlsx',demoFMT(),'financial');const p=s.workspace.projects[0];p.serviceModel={...p.serviceModel,staff:[],pathways:[{id:'linked-path',name:'Question-linked service pathway',description:'Synthetic pathway',questionIds:['q01']}]};p.fmt={fileId:externalId,name:'Completed fixture',fingerprint:createHash('sha256').update(demoFMT()).digest('hex'),sheets:[{name:'Inputs',rows:4,columns:7}],mappings:[],mode:'completed',completedFacts:[{id:'price',label:'Year 1 price',sheet:'Inputs',cell:'F1',verified:true}],status:'draft',validatedHash:'',validationNote:'',exportedHash:''};p.deadline={date:'2026-10-15',time:'17:00',timezone:'Europe/London',sourceId:'',locator:'Synthetic deadline',confirmed:true,updatedAt:new Date().toISOString()};await put(s);
 await act(master,'/api/fmt',{action:'validate',projectId:'winchester'});s=await state();let r=await mf.dispatchFetch(origin+'/api/fmt',{method:'POST',headers:{...identity(master),Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({action:'export',projectId:'winchester',revision:s.revision})});assert.equal(r.status,200);const copy=new Uint8Array(await r.arrayBuffer());assert.equal(createHash('sha256').update(copy).digest('hex'),createHash('sha256').update(demoFMT()).digest('hex'));await act(master,'/api/workflow',{action:'check',projectId:'winchester',targetId:'_fmt'});await act(master,'/api/workflow',{action:'approve',projectId:'winchester',targetId:'_fmt',confirmRecalculated:true,note:'Synthetic saved price independently checked.'});s=await state();assert.equal(s.workspace.projects[0].fmt.status,'approved');assert.equal(s.workspace.projects[0].facts[0].value,'999');assert.match(s.workspace.projects[0].facts[0].locator,/Inputs!F1/);
 const finalId=await upload('final.txt',Buffer.from('PRIVATE-COMPLETED-EXTRACT'),'completed');s=await state();s.workspace.sources.push({id:'completed-source',name:'Final file',text:'PRIVATE-COMPLETED-EXTRACT',kind:'Completed bid context',scope:'global',status:'needs_verification',visibility:'master',category:'completed',fileId:finalId,locator:'Final fixture',createdAt:new Date().toISOString(),origin:{kind:'completed_bid',recordId:finalId,period:'',version:'1',retrievedAt:new Date().toISOString(),projectId:'winchester'}});await put(s);assert.ok(!JSON.stringify(await req(writer,'/api/workspace')).includes('PRIVATE-COMPLETED-EXTRACT'));r=await mf.dispatchFetch(origin+'/api/files?id='+finalId,{headers:identity(writer)});assert.equal(r.status,404);await r.text();
 let review=await req(master,'/api/post-bid?projectId=winchester');review.review.teamFeedback='PRIVATE-MASTER-FEEDBACK';await req(master,'/api/post-bid',{projectId:'winchester',review:review.review,reviewRevision:0});await req(master,'/api/post-bid',{projectId:'winchester',review:review.review,reviewRevision:0},409);assert.ok(!JSON.stringify(await req(writer,'/api/workspace')).includes('PRIVATE-MASTER-FEEDBACK'));assert.ok(!JSON.stringify(await req(writer,'/api/collaboration')).includes('PRIVATE-MASTER-FEEDBACK'));
 s=await state();const removed=structuredClone(s);removed.workspace.projects[0].questions=removed.workspace.projects[0].questions.slice(1);await req(master,'/api/workspace',{workspace:removed.workspace,revision:s.revision},400,'PUT');await act(master,'/api/bids',{action:'deleteQuestion',projectId:'winchester',questionId:'q01',confirm:'wrong'},400);await act(master,'/api/bids',{action:'deleteQuestion',projectId:'winchester',questionId:'q01',confirm:s.workspace.projects[0].questions[0].ref});assert.ok(!(await state()).collaboration.assignments.some(a=>a.targetId==='q01'));assert.equal((await state()).workspace.projects[0].fmt.status,'draft');assert.equal((await state()).workspace.projects[0].facts.length,0);
 const ittId=await upload('tender.txt',Buffer.from('Tender deadline 15 Oct 2026'),'itt');s=await state();s.workspace.sources.push({id:'tender',name:'Tender file',text:'Tender deadline',kind:'Tender requirement',scope:'winchester',status:'needs_verification',fileId:ittId,category:'itt',locator:'',createdAt:''});s.workspace.projects[0].deadline.sourceId='tender';await put(s);await act(master,'/api/bids',{action:'deleteDocument',projectId:'winchester',sourceId:'tender',confirm:'Tender file'});assert.equal((await state()).workspace.projects[0].deadline.confirmed,false);r=await mf.dispatchFetch(origin+'/api/files?id='+ittId,{headers:identity(master)});assert.equal(r.status,404);await r.text();
 await act(master,'/api/bids',{action:'archive',projectId:'winchester',note:'Synthetic archived bid for regression checks.'});assert.equal((await state()).workspace.projects.length,0);const archive=await req(master,'/api/bids?id=winchester');assert.equal(archive.body.workspace.projects[0].fmt.mode,'completed');review=await req(master,'/api/post-bid?projectId=winchester');assert.equal(review.review.teamFeedback,'PRIVATE-MASTER-FEEDBACK');r=await mf.dispatchFetch(origin+'/api/files?id='+externalId,{headers:identity(writer)});assert.equal(r.status,404);await r.text();r=await mf.dispatchFetch(origin+'/',{headers:identity(master)});assert.equal(r.status,200);await r.text();
 await act(master,'/api/bids',{action:'restore',projectId:'winchester'});s=await state();assert.equal(s.workspace.projects.length,1);assert.equal(s.workspace.projects[0].fmt.status,'draft');assert.equal(s.workspace.projects[0].modelSourceId,null);assert.equal(s.collaboration.assignments.length,0);await act(master,'/api/bids',{action:'deleteBid',projectId:'winchester',confirm:s.workspace.projects[0].name});assert.equal((await state()).workspace.projects.length,0);r=await mf.dispatchFetch(origin+'/api/files?id='+finalId,{headers:identity(master)});assert.equal(r.status,200);assert.equal(await r.text(),'PRIVATE-COMPLETED-EXTRACT');
 console.log('PASS: master-only lifecycle actions and reusable evidence; private completed files and post-bid review; private-review stale writes; external FMT exact copy and actual saved facts; mandatory deletion confirmations; deadline invalidation; last-bid archive/restore/delete; archive file privacy; retained reusable originals.');
}finally{await mf.dispose();}
