import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import ts from 'typescript';
import {SignJWT,generateKeyPair,exportJWK,createLocalJWKSet} from 'jose';
import {demoModel,demoFMT,demoMappings} from './demo-fixture.mjs';
await fs.mkdir('work/test-modules',{recursive:true});
for(const name of ['finance','xlsx','itt','access-auth','state','deadlines','staff-import','post-bid']){const source=await fs.readFile('lib/'+name+'.ts','utf8');let code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;code=code.replace(/from ['"]\.\/(finance|xlsx|itt|access-auth|state|deadlines|staff-import|post-bid)['"]/g,(_,n)=>`from './${n}.mjs'`);await fs.writeFile('work/test-modules/'+name+'.mjs',code);}
const f=await import('../work/test-modules/finance.mjs');const x=await import('../work/test-modules/xlsx.mjs');const itt=await import('../work/test-modules/itt.mjs');const auth=await import('../work/test-modules/access-auth.mjs');
const st=await import('../work/test-modules/state.mjs');const baseline={projects:[{id:'bid',brief:{summary:'Before'},questions:[{id:'q1',draft:'Sent for save',status:'review'}]}]};const server=structuredClone(baseline);server.projects[0].brief.summary='Updated from the question';server.projects[0].questions[0].status='draft';const typing=structuredClone(baseline);typing.projects[0].questions[0].draft+=' then more typing';const merged=st.reconcileSaved(server,baseline,typing);assert.equal(merged.projects[0].brief.summary,'Updated from the question');assert.equal(merged.projects[0].questions[0].status,'draft');assert.equal(merged.projects[0].questions[0].draft,'Sent for save then more typing');assert.equal(await f.contentHash({a:1,b:2}),await f.contentHash({b:2,a:1}));
const m=demoModel();const result=f.calculateModel(m);assert.equal(result.rows[0].tupeWte,1);assert.equal(result.rows[0].recruitWte,1);assert.equal(result.years[0].staff,96750);assert.equal(result.years[0].nonPay,4000);assert.equal(result.years[0].price,132990);assert.deepEqual(f.modelIssues(m),[]);
const margin=structuredClone(m);margin.pricingMethod='margin';assert.equal(f.calculateModel(margin).years[0].price,138531.25);margin.profitPct=100;assert.equal(f.calculateModel(margin).years[0].price,null);assert.ok(f.modelIssues(margin).some(i=>i.includes('below 100')));
const missing=structuredClone(m);missing.staff[0].salaryFte=null;assert.equal(f.calculateModel(missing).years[0].price,null);
const excess=structuredClone(m);excess.tupe[0].fte=3;assert.ok(f.modelIssues(excess).some(i=>i.includes('exceeds')));
const unmatched=structuredClone(m);unmatched.tupe[0].staffLineId='unknown';assert.equal(f.calculateModel(unmatched).years[0].staff,null);
const coverage=structuredClone(m);coverage.staff[0].basis='coverage';coverage.staff[0].weeklyCoverage=75;assert.ok(Math.abs(f.staffWte(coverage.staff[0],coverage)-75*52.14/(37.5*46))<1e-12);
const book=x.readWorkbook(demoFMT());const plan={fileId:'fixture',mappings:demoMappings()};assert.deepEqual(x.validateMappings(book,m,plan),[]);
for(const [cell,reason] of [['F1','formula'],['G1','locked'],['A4','merged']]){const bad={...plan,mappings:[{...plan.mappings[0],cell}]};assert.ok(x.validateMappings(book,m,bad).some(s=>s.toLowerCase().includes(reason)));}
const filled=x.fillFMT(demoFMT(),m,plan);const after=x.readWorkbook(filled);assert.equal(after.sheets[0].cells.find(c=>c.ref==='B1').value,'96750');assert.equal(after.sheets[0].cells.find(c=>c.ref==='F1').formula,'SUM(B1,C1:C2,D1,E1)');assert.equal(after.sheets[0].cells.find(c=>c.ref==='F1').value,'');assert.equal(after.sheets[0].cells.find(c=>c.ref==='G1').value,'123');await fs.writeFile('work/test-costed-FMT.xlsx',filled);
const questions=itt.extractQuestions('[Page 1]\nQ01 - Service delivery\nDescribe your service. Maximum 2,000 words.\nQ02 - Governance\nExplain assurance. Limit 15,750 characters including spaces.');assert.equal(questions.length,2);assert.equal(questions[0].limit,2000);assert.equal(questions[0].unit,'words');assert.equal(questions[1].limit,15750);
const {publicKey,privateKey}=await generateKeyPair('RS256');const jwk=await exportJWK(publicKey);jwk.kid='fixture-key';const keys=createLocalJWKSet({keys:[jwk]});const issuer='https://testteam.cloudflareaccess.com';const token=await new SignJWT({email:'writer@example.test'}).setProtectedHeader({alg:'RS256',kid:'fixture-key'}).setIssuer(issuer).setAudience('test-aud').setSubject('fixture-user').setIssuedAt().setExpirationTime('2m').sign(privateKey);assert.equal((await auth.verifyAccessToken(token,issuer,'test-aud',keys)).email,'writer@example.test');await assert.rejects(auth.verifyAccessToken(token,issuer,'wrong-aud',keys));await assert.rejects(auth.verifyAccessToken(token,issuer.replace('testteam','wrongteam'),'test-aud',keys));const damaged=token.split('.');damaged[2]=(damaged[2][0]==='A'?'B':'A')+damaged[2].slice(1);await assert.rejects(auth.verifyAccessToken(damaged.join('.'),issuer,'test-aud',keys));
console.log('PASS: TUPE offsets recruitment; missing costs stay unavailable; margin/markup; coverage WTE; guarded workbook inputs; formula preservation/cache clearing; ITT limits; verified JWT issuer/audience/signature.');

const deadlines=await import('../work/test-modules/deadlines.mjs'),staffImport=await import('../work/test-modules/staff-import.mjs');
const dl={date:'2026-10-15',time:'17:00',timezone:'Europe/London',sourceId:'doc',locator:'Page 1',confirmed:true,updatedAt:''};assert.equal(new Date(deadlines.deadlineInstant(dl)).toISOString(),'2026-10-15T16:00:00.000Z');assert.equal(deadlines.countdown(dl,new Date('2026-10-02T12:00:00Z')).days,13);assert.equal(deadlines.countdown({...dl,confirmed:false}).days,null);assert.equal(deadlines.deadlineInstant({...dl,date:'2026-03-29',time:'01:30'}),null);assert.equal(deadlines.deadlineInstant({...dl,date:'2026-02-30'}),null);const candidates=deadlines.extractDeadlines([{id:'doc',text:'The tender submission deadline is 15th October 2026 at 5pm.\nClarifications close 10 October 2026.'}]);assert.ok(candidates.some(c=>c.date==='2026-10-15'&&c.time==='17:00'));
const sBook=structuredClone(book);sBook.sheets=[{...book.sheets[0],name:'Staff',cells:[{ref:'A1',value:'Role'},{ref:'B1',value:'WTE'},{ref:'C1',value:'Annual salary'},{ref:'D1',value:'Employer pension %'},{ref:'A2',value:'Nurse'},{ref:'B2',value:'2'},{ref:'C2',value:'80000'},{ref:'D2',value:'0.05'},{ref:'A3',value:'Total'},{ref:'B3',value:'2'}].map(c=>({...c,formula:'',style:0})),rows:3,columns:4}];const sm=staffImport.suggestStaffMapping(sBook);assert.equal(sm.header,1);sm.salaryBasis='actual_annual';sm.percentUnits='fraction';const imported=staffImport.importStaff(sBook,sm,{...m,staff:[]});assert.equal(imported.length,1);assert.equal(imported[0].line.salaryFte,40000);assert.equal(imported[0].line.pensionPct,5);assert.equal(imported[0].line.niPct,null);assert.ok(imported[0].warnings.some(w=>w.includes('employer NI')));assert.throws(()=>staffImport.importStaff(sBook,{...sm,paidWeeks:99},m));
const external={mode:'completed',fileId:'fixture',fingerprint:'hash',completedFacts:[{id:'total',label:'Year 1 price',sheet:'Inputs',cell:'F1',verified:true}],mappings:[]};assert.deepEqual(f.fmtIssues({fmt:external}),[]);assert.equal(x.completedWorkbookFacts(book,external)[0].value,'999');assert.throws(()=>x.completedWorkbookFacts(after,external),/Recalculate/);assert.throws(()=>x.completedWorkbookFacts(book,{...external,completedFacts:[{...external.completedFacts[0],cell:'XFE1'}]}),/valid/);
console.log('PASS: London deadline/DST validation; extracted deadline candidates; staff mapping and actual-pay conversion; explicit missing inputs; completed FMT saved-value provenance.');
